spring:


  datasource:
    url: jdbc:mysql://121.199.2.219/ffAid?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: ffaid
    password: Zz894833959
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    timeout: 20000
#    #    集群环境打开下面注释，单机不需要打开
#    #    cluster:
#    #      集群信息
#    #      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
#    #      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
#    #      maxRedirects: 3
#    pool:
#
#      max-active: 8
#      min-idle: 0
#      max-idle: 8
#      max-wait: -1
#    password:




mybatis:
  type-aliases-package: com.example.ffaid.domain
  mapper-locations: classpath:mapping/*.xml

server:
  port: 8080
  address: 0.0.0.0


